-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."User"
(
    "Id" serial NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Surname" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "Password" character varying(255) NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Sensor"
(
    "Id" serial NOT NULL,
    "Name" character varying(255) NOT NULL,
    CONSTRAINT id_sensor PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Wine"
(
    "Id" serial NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Year" integer NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Medition"
(
    "Year" integer NOT NULL,
    "Id_sensor" serial NOT NULL,
    "Id_wine" serial NOT NULL,
    "Colour" character varying(255) NOT NULL,
    "Graduation" integer NOT NULL,
    "Ph" integer NOT NULL,
    PRIMARY KEY ("Id_sensor", "Id_wine")
);

ALTER TABLE IF EXISTS public."Medition"
    ADD CONSTRAINT id_sensor FOREIGN KEY ("Id_sensor")
    REFERENCES public."Sensor" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Medition"
    ADD CONSTRAINT id_wine FOREIGN KEY ("Id_wine")
    REFERENCES public."Wine" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;