nelmio_api_doc:
    documentation:
        info:
            title: API Docs
            description: This is an awesome app!
            version: 1.0.0
        components:
            schemas:
                UserLogin:
                    type: object
                    properties:
                        email: {type: string, example: "example123@gmail.com"}
                        password: {type: string, example: "example123"}
                
                SensorRegister:
                    type: object
                    properties:
                        name: {type: string, example: "ExampleSensor"}

    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
        wines_project:
            with_annotation: true
